apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: memcached-operator-subsription
  namespace: op
spec:
  channel: stable
  name: memcached-operator
  source: harbor
  sourceNamespace: olm
